@rootURL = http://localhost:5265

GET {{rootURL}}/weatherforecast/
Accept: application/json

###
GET {{rootURL}}/api/Trashbin
Accept: application/json

###
GET {{rootURL}}/api/Trashbin/12
Accept: application/json

###
POST {{rootURL}}/api/Trashbin
Content-Type: application/json
{
    "trashbinId": 67,
    "binIntegrity": 0,
    "bodyColor": "red",
    "storageSizeInLiters": 4,
    "location": "library 1st floor",
    "createdAt": "2025-11-05T14:50:39.8823737+08:00",
    "updatedAt": "2025-11-05T14:50:39.8823912+08:00"
}